on: [push, pull_request]
name: Build
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: go test -race -v ./... -coverprofile ./coverage.txt

  codecov:
    name: Upload coverage report to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./

      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          files: ./coverage.txt
          fail_ci_if_error: true
          verbose: true